baseURL: https://benno.app/
languageCode: en-us
title: iBenno
theme: "PaperMod"

# Build settings
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

params:
  title: iBenno
  description: "A viewfinder for iBenno"
  keywords: [Blog, Portfolio, PaperMod, Programming, Engineering, Technology, Science, Math]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2023"

menu:
  main:
    - identifier: categories
      name: categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: tags
      url: /tags/
      weight: 20
    - identifier: Benno
      name: benno.app
      url: https://benno.app
      weight: 30

# Syntax highlighting
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
