# Site configuration
baseURL: https://benno.app/
languageCode: en-us
title: Benno
theme: "PaperMod"

# Content configuration
paginate: 10
contentDir:
  - "docs"
  - "posts"
homeSections:
  - "posts"
  - "docs"

# Build settings
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Minification settings
minify:
  disableXML: true
  minifyOutput: true

# Site parameters
params:
  # SEO settings
  description: "A viewfinder for iBenno"
  keywords:
    - "Blog"
    - "Portfolio"
    - "PaperMod"
    - "Programming"
    - "Engineering"
    - "Technology"
    - "Science"
    - "Math"
  images:
    - "<link or path of image for opengraph, twitter-cards>"
  timeZone: "Europe/Stockholm"
  dateFormat: "2006-01-02 kl. 15:04"
  enableDarkMode: "auto"

  # Home page settings
  ShowPostNavLinks: true
  ShowBreadCrumbs: false # Show breadcrumbs on top of the page
  ShowCodeCopyButtons: true 
  UseHugoToc: true # Use Hugo's built-in table of contents
  tocLevels: "2..6"

  # Post metadata settings
  hidemeta: true      # Hide metadata such as date, author, tags, categories
  hideSummary: false  # Hide the summary as in the first paragraph of the post
  
  # Home page info
  homeInfoParams:
    Title: "Hi there \U0001F60F" 
    Content: "Welcome to my site!"

  # Social icons
  socialIcons:
    - name: "github"
      url: "https://github.com/benno657"
    - name: "discord"
      url: "http://discordapp.com/users/Benno#5267"
    - name: "instagram"
      url: "http://instagram.com/bnossbring"
    - name: "linkedin" 
      url: "https://www.linkedin.com/in/benjamin-nossbring-a735a3198/"

  # Cover settings
  cover:
    hidden: true # Hide everywhere but not in structured data
    hiddenInList: true # Hide on list pages and home
    hiddenInSingle: true # Hide on single page

  # Edit post settings
#  editPost:
#    URL: "https://github.com/benno657/benno657.github.io/content"
#    Text: "Suggest Changes" # Edit text
#    appendFilePath: true # To append file path to Edit link

# Main menu settings
menu:
  main:
    - identifier: "categories"
      name: "Categories"
      url: "/categories/"
      weight: 10
    - identifier: "tags"
      name: "Tags"
      url: "/tags/"
      weight: 20
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 30

# Syntax highlighting
markup:
  highlight:
    noClasses: false
    # anchorLineNos: true 
    # codeFences: true
    guessSyntax: true
    # lineNos: true
    # style: "monokai"
