baseURL: https://benno.app/
languageCode: en-us
title: Benno
theme: "PaperMod"
paginate: 10
contentDir: ["docs", "posts"] # show both docs and posts
# content on the home page
homeSections:
  - posts
  - docs


# Build settings
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  description: "A viewfinder for iBenno"
  keywords: [Blog, Portfolio, PaperMod, Programming, Engineering, Technology, Science, Math]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  timeZone: "Europe/Stockholm"
  dateFormat: "2006-01-02 kl. 15:04"

  ShowPostNavLinks: true
  ShowBreadCrumbs: true # Show breadcrumbs on top of the page
  #ShowWordCount: true
  ShowCodeCopyButtons: true 
  UseHugoToc: true # Use Hugo's built-in table of contents
  # toc levels
  tocLevels: "2..6"
  hidemeta: false # metadata as in date, author, tags, categories
  hideSummary: false # summary as in the first paragraph of the post
  
  # home-info mode
  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: Welcome to my site!

  socialIcons:
    - name: github
      url: "https://github.com/"
    - name: linkedin
      url: "https://www.linkedin.com/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

  editPost:
    URL: "https://github.com/benno657/benno657.github.io/content"
    Text: "Suggest Changes" # edit text
    appendFilePath: true # to append file path to Edit link
  


menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10

    - identifier: tags
      name: tags
      url: /tags/
      weight: 20

    - identifier: about
      name: about
      url: /about/
      weight: 30

# Read: https://github.com/adityatelange/hugo-PaperMod/wiki/FAQs#using-hugos-syntax-highlighter-chroma
# Syntax highlighting
pygmentsUseClasses: true

markup:
  highlight:
    noClasses: false
    # anchorLineNos: true
    # codeFences: true
    # guessSyntax: true
    # lineNos: true
    # style: monokai
